/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 
 I Love Kotlin - NekoIceCream
 */

package learnkotlin.kotlin

class App 
{
    val greeting: String
        get() {
            return "Hello "
    }
}

fun main() 
{
    var vocal = 'A'
    val name = "NekoIceCream "
    println("Vocal " + vocal++)
    println("Vocal " + vocal++)
    println("Vocal " + vocal++)
    println("Vocal " + vocal--)
    println("Vocal " + vocal--)
    println("Vocal " + vocal--)
    println("Vocal " + vocal--)
    
    print(App().greeting)
    print(name)
    println(if (true) "Always true" else "Always false")
}