/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 
 I Love Kotlin - NekoIceCream
 */

package learnkotlin.kotlin

class App {
    val greeting: String
        get() {
            return "Hello"
}
}

fun main() {
    val name = "NekoIceCream "
    print(App().greeting)
    print(name)
    println(if (true) "Always true" else "Always false")
}
